### ISSUE TITLE
Grid & Layout

### ISSUE THREAD

**Issue by dimonka83** [qiwi/pijma#145]
http://qiwiguide.ru/grid/

**Comment by dimonka83** [comment]
```ts
interface GridProps {
  gutter?: number
  columns?: number
  layout?: number[]
}
```

```tsx
const Grid = ({gutter = 20, columns = 12, layout = [1]}) => (
  <Flex wrap="wrap">
    {Reac.Children.map(children, (child, index) => (
      <FlexItem
        width={WIDTH_IN_PERCENT_DEPENDS_ON_GUTTER_COLUMNS_LAYOUT}
        mt={GUTTER_TOP_EXCEPT_FIRST_ROW_ELEMENTS}
        ml={GUTTER_LEFT_EXCEPT_EACH_ROW_FIRST_ELEMENTS}>
        children={child}
      />
    )}
  </Flex>
)
```

**Comment by dimonka83** [comment]
![image](https://user-images.githubusercontent.com/4487029/58799616-78735800-860e-11e9-8e8d-1a9b117407cf.png)

`<Grid layout={[1, 7, 4]}/>`

![image](https://user-images.githubusercontent.com/4487029/58799763-ce480000-860e-11e9-8f22-c84f27d390c4.png)

![image](https://user-images.githubusercontent.com/4487029/58799777-dd2eb280-860e-11e9-989c-db2ab39b8455.png)

`<Grid layout={[2]}/>`

**Comment by dimonka83** [comment]
![image](https://user-images.githubusercontent.com/4487029/58800346-4b27a980-8610-11e9-9f80-57f13bdce6b3.png)

`<Grid columns={5} layout={[1]}/>`

**Comment by anastasia-gorshkova** [comment]
#163

**Comment by dimonka83** [comment]
#163
