### ISSUE TITLE
v2

### ISSUE THREAD

**Issue by dimonka83** [qiwi/pijma#159]
* theming? different themes (set of colors, resolutions) for different guides (qiwi, sovest, investor)... no common theme is available?
* adaptive: mobile and desktop - all in one component
  * semantic (good for different layout, problems with 99% same same components):
    ```
    <MediaQuery minDeviceWidth={...}>
      <Btn width="auto"/>
    </MediaQuery>
    <MediaQuery minDeviceWidth={...}>
      <Btn width="100%"/>
    </MediaQuery>
    ```
  * props (problem with no common theme, good for 99% same same components):
    ```
    <Btn width={{xs:'100%',m:'auto'}}/> // xs, m - keys of `theme.devices`, order does not matter
    <Btn width={['100%','auto']}/> // index - indexes of `theme.devices`, order matters
    ```
  * hooks (weird is a problem?) 
    ```
    // props
    const Button = ({children}) => {
      const isDesktop = useMediaQuery({minWidth: ...})
      return <Btn with={isDesktop ? 'auto' : '100%}/>
    }
    // semantic
    const Button = ({children}) => {
      const isDesktop = useMediaQuery({minWidth: ...})
      if (isDesktop) {
        return <Btn with="auto"/>
      }
      return <Btn with="100%"/>
    }
    ```
  * what`s about components which have only mobile or desktop presentation?
* one component - one package
* one synchronous release of all packages
* packages structure is:
  * `@qiwi/pijma` - monorepo of primitives and controls
    * `@qiwi/pijma-primitives` or `@qiwi/pijma-atoms`  - primitives or atoms package
    * `@qiwi/pijma-button` - button control package
  * `@qiwi/qw-pijma` - monorepo of qiwi wallet guide components (maybe with dark mode)
    * `@qiwi/qw-pijma-button` or `@qiwi/qw-button` - qiwi wallet button package
  * `@qiwi/so-pijma` - monorepo of sovest guide components
    * `@qiwi/so-pijma-button` or `@qiwi/so-button` - sovest button package

**Comment by dimonka83** [comment]
* extra primitives (Block, Section, MenuItem, DumpButton, DumpLink)
  * have states (active, hover, focus, disabled)
  * can be rendered as button (form button), link (with href), action (like link without href or button out of form)
  * controlled by buttoncontrol, linkcontrol, actioncontrol
  * auto appends suitable html attributes (title, href from links, type from button)

**Comment by dimonka83** [comment]
- using react hooks?

**Comment by dimonka83** [comment]
* common box (no card, pos, flex, etc...)
* special styles filtered by display with discriminated unions (top, right, bottom and left applied to position elements only)

**Comment by Spetruk** [comment]
- accessibilityIdentifier для компонентов

**Comment by dimonka83** [comment]
- react-spectrum?

**Comment by asan** [comment]
> * react-spectrum?

@dimonka83 react-spectrum or  React Aria? 

- storybook
- screenshot testing
- deprecate `<Glossary children={[{title: "qwe", content: "..."}]} />` pattern in favor of something like:
  -  `<Glossary><Glossary.Item title="qwe">...</Glossary.Item></Glossary>`
- make `Tabs` router friendly
- export everything from one package

**Comment by dimonka83** [comment]
одной только @react-aria не обойдешься, там же куча зависимостей, считай весь @react-spectrum и затягиваешь (без юай)

**Comment by dimonka83** [comment]
- css-in-js? emotion-js, styled-components, linaria, goober...? weird. slow. our own? :)

**Comment by dimonka83** [comment]
- several versions of component? button v1, next major update, button v2... do we need support button v1?

**Comment by dimonka83** [comment]
- theme by component - ButtonTheme
- full guide bundle theme merge from dependend component themes
- base themes ColorTheme, SizeTheme, ButtonTheme extends ColorTheme, SizeTheme

**Comment by Nio-o** [comment]
- scss modules or something like linaria
- reduce amount of code relative to v1. I mean this is hard to contribute because code of one component split between `core` and `mobile/desktop` packages.
- avoid code with side-effects like `injectGlobal`, `applyDefaultClickHandler`
- links. Use `<a>` inside `<Link>` instead of `applyDefaultClickHandler` or maybe another approach
