### ISSUE TITLE
Migrate to styled-components?

### ISSUE THREAD

**Issue by dimonka83** [qiwi/pijma#84]
**Why?**
* [style objects](https://www.styled-components.com/docs/advanced#style-objects)
* [typescript](https://www.styled-components.com/docs/api#typescript)
* [as](https://www.styled-components.com/docs/api#as-polymorphic-prop) vs [withComponent](https://emotion.sh/docs/styled#change-the-rendered-tag-using-withcomponent)
* :four: &times; :star: = :trollface:

**Comment by antongolub** [comment]
Approved.
